[package]
name = "candid_extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
wasmtime = "11.0.1"

[workspace]
members = ["canister"]
